#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-ThinItalic24");
#define AILERON_THINITALIC_HANDLE 0
#define AILERON_THINITALIC_WIDTH 21
#define AILERON_THINITALIC_HEIGHT 29
#define AILERON_THINITALIC_CELLS 96
#define ASSETS_END 30772UL
static const shape_t AILERON_THINITALIC_SHAPE = {0, 21, 29, 0};
