#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-LightItalic18");
#define AILERON_LIGHTITALIC_HANDLE 0
#define AILERON_LIGHTITALIC_WIDTH 17
#define AILERON_LIGHTITALIC_HEIGHT 22
#define AILERON_LIGHTITALIC_CELLS 96
#define ASSETS_END 19156UL
static const shape_t AILERON_LIGHTITALIC_SHAPE = {0, 17, 22, 0};
