#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLightItalic18");
#define AILERON_ULTRALIGHTITALIC_HANDLE 0
#define AILERON_ULTRALIGHTITALIC_WIDTH 16
#define AILERON_ULTRALIGHTITALIC_HEIGHT 22
#define AILERON_ULTRALIGHTITALIC_CELLS 96
#define ASSETS_END 17044UL
static const shape_t AILERON_ULTRALIGHTITALIC_SHAPE = {0, 16, 22, 0};
