#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLight36");
#define AILERON_ULTRALIGHT_HANDLE 0
#define AILERON_ULTRALIGHT_WIDTH 30
#define AILERON_ULTRALIGHT_HEIGHT 43
#define AILERON_ULTRALIGHT_CELLS 96
#define ASSETS_END 62068UL
static const shape_t AILERON_ULTRALIGHT_SHAPE = {0, 30, 43, 0};
