#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBoldItalic9");
#define AILERON_SEMIBOLDITALIC_HANDLE 0
#define AILERON_SEMIBOLDITALIC_WIDTH 10
#define AILERON_SEMIBOLDITALIC_HEIGHT 11
#define AILERON_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t AILERON_SEMIBOLDITALIC_SHAPE = {0, 10, 11, 0};
