#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLightItalic36");
#define AILERON_ULTRALIGHTITALIC_HANDLE 0
#define AILERON_ULTRALIGHTITALIC_WIDTH 30
#define AILERON_ULTRALIGHTITALIC_HEIGHT 43
#define AILERON_ULTRALIGHTITALIC_CELLS 96
#define ASSETS_END 62068UL
static const shape_t AILERON_ULTRALIGHTITALIC_SHAPE = {0, 30, 43, 0};
