#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-blackItalic12");
#define AILERON_BLACKITALIC_HANDLE 0
#define AILERON_BLACKITALIC_WIDTH 13
#define AILERON_BLACKITALIC_HEIGHT 14
#define AILERON_BLACKITALIC_CELLS 96
#define ASSETS_END 9556UL
static const shape_t AILERON_BLACKITALIC_SHAPE = {0, 13, 14, 0};
