#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-HeavyItalic24");
#define AILERON_HEAVYITALIC_HANDLE 0
#define AILERON_HEAVYITALIC_WIDTH 24
#define AILERON_HEAVYITALIC_HEIGHT 29
#define AILERON_HEAVYITALIC_CELLS 96
#define ASSETS_END 33556UL
static const shape_t AILERON_HEAVYITALIC_SHAPE = {0, 24, 29, 0};
