#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-blackItalic18");
#define AILERON_BLACKITALIC_HANDLE 0
#define AILERON_BLACKITALIC_WIDTH 19
#define AILERON_BLACKITALIC_HEIGHT 22
#define AILERON_BLACKITALIC_CELLS 96
#define ASSETS_END 21268UL
static const shape_t AILERON_BLACKITALIC_SHAPE = {0, 19, 22, 0};
