#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-ThinItalic12");
#define AILERON_THINITALIC_HANDLE 0
#define AILERON_THINITALIC_WIDTH 11
#define AILERON_THINITALIC_HEIGHT 14
#define AILERON_THINITALIC_CELLS 96
#define ASSETS_END 8212UL
static const shape_t AILERON_THINITALIC_SHAPE = {0, 11, 14, 0};
