#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-LightItalic36");
#define AILERON_LIGHTITALIC_HANDLE 0
#define AILERON_LIGHTITALIC_WIDTH 33
#define AILERON_LIGHTITALIC_HEIGHT 43
#define AILERON_LIGHTITALIC_CELLS 96
#define ASSETS_END 70324UL
static const shape_t AILERON_LIGHTITALIC_SHAPE = {0, 33, 43, 0};
