#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-HeavyItalic18");
#define AILERON_HEAVYITALIC_HANDLE 0
#define AILERON_HEAVYITALIC_WIDTH 19
#define AILERON_HEAVYITALIC_HEIGHT 22
#define AILERON_HEAVYITALIC_CELLS 96
#define ASSETS_END 21268UL
static const shape_t AILERON_HEAVYITALIC_SHAPE = {0, 19, 22, 0};
