#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-HeavyItalic9");
#define AILERON_HEAVYITALIC_HANDLE 0
#define AILERON_HEAVYITALIC_WIDTH 10
#define AILERON_HEAVYITALIC_HEIGHT 11
#define AILERON_HEAVYITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t AILERON_HEAVYITALIC_SHAPE = {0, 10, 11, 0};
