#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-LightItalic24");
#define AILERON_LIGHTITALIC_HANDLE 0
#define AILERON_LIGHTITALIC_WIDTH 22
#define AILERON_LIGHTITALIC_HEIGHT 29
#define AILERON_LIGHTITALIC_CELLS 96
#define ASSETS_END 30772UL
static const shape_t AILERON_LIGHTITALIC_SHAPE = {0, 22, 29, 0};
