#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-LightItalic12");
#define AILERON_LIGHTITALIC_HANDLE 0
#define AILERON_LIGHTITALIC_WIDTH 11
#define AILERON_LIGHTITALIC_HEIGHT 14
#define AILERON_LIGHTITALIC_CELLS 96
#define ASSETS_END 8212UL
static const shape_t AILERON_LIGHTITALIC_SHAPE = {0, 11, 14, 0};
