#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLight18");
#define AILERON_ULTRALIGHT_HANDLE 0
#define AILERON_ULTRALIGHT_WIDTH 15
#define AILERON_ULTRALIGHT_HEIGHT 22
#define AILERON_ULTRALIGHT_CELLS 96
#define ASSETS_END 17044UL
static const shape_t AILERON_ULTRALIGHT_SHAPE = {0, 15, 22, 0};
