#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeBold18");
#define COURIER PRIME BOLD_HANDLE 0
#define COURIER PRIME BOLD_WIDTH 12
#define COURIER PRIME BOLD_HEIGHT 18
#define COURIER PRIME BOLD_CELLS 96
#define ASSETS_END 10516UL
static const shape_t COURIER PRIME BOLD_SHAPE = {0, 12, 18, 0};
