#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeBold12");
#define COURIER PRIME BOLD_HANDLE 0
#define COURIER PRIME BOLD_WIDTH 9
#define COURIER PRIME BOLD_HEIGHT 12
#define COURIER PRIME BOLD_CELLS 96
#define ASSETS_END 5908UL
static const shape_t COURIER PRIME BOLD_SHAPE = {0, 9, 12, 0};
