#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeBoldItalic12");
#define COURIER PRIME BOLD ITALIC_HANDLE 0
#define COURIER PRIME BOLD ITALIC_WIDTH 9
#define COURIER PRIME BOLD ITALIC_HEIGHT 12
#define COURIER PRIME BOLD ITALIC_CELLS 96
#define ASSETS_END 5908UL
static const shape_t COURIER PRIME BOLD ITALIC_SHAPE = {0, 9, 12, 0};
