#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeItalic18");
#define COURIER PRIME ITALIC_HANDLE 0
#define COURIER PRIME ITALIC_WIDTH 13
#define COURIER PRIME ITALIC_HEIGHT 18
#define COURIER PRIME ITALIC_CELLS 96
#define ASSETS_END 12244UL
static const shape_t COURIER PRIME ITALIC_SHAPE = {0, 13, 18, 0};
