#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeItalic12");
#define COURIER PRIME ITALIC_HANDLE 0
#define COURIER PRIME ITALIC_WIDTH 9
#define COURIER PRIME ITALIC_HEIGHT 12
#define COURIER PRIME ITALIC_CELLS 96
#define ASSETS_END 5908UL
static const shape_t COURIER PRIME ITALIC_SHAPE = {0, 9, 12, 0};
