#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeBoldItalic24");
#define COURIER PRIME BOLD ITALIC_HANDLE 0
#define COURIER PRIME BOLD ITALIC_WIDTH 18
#define COURIER PRIME BOLD ITALIC_HEIGHT 24
#define COURIER PRIME BOLD ITALIC_CELLS 96
#define ASSETS_END 20884UL
static const shape_t COURIER PRIME BOLD ITALIC_SHAPE = {0, 18, 24, 0};
