#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBoldItalic36");
#define CRIMSONTEXT_SEMIBOLDITALIC_HANDLE 0
#define CRIMSONTEXT_SEMIBOLDITALIC_WIDTH 36
#define CRIMSONTEXT_SEMIBOLDITALIC_HEIGHT 49
#define CRIMSONTEXT_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 84820UL
static const shape_t CRIMSONTEXT_SEMIBOLDITALIC_SHAPE = {0, 36, 49, 0};
