#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-BoldItalic24");
#define CRIMSONTEXT_BOLDITALIC_HANDLE 0
#define CRIMSONTEXT_BOLDITALIC_WIDTH 25
#define CRIMSONTEXT_BOLDITALIC_HEIGHT 30
#define CRIMSONTEXT_BOLDITALIC_CELLS 96
#define ASSETS_END 37588UL
static const shape_t CRIMSONTEXT_BOLDITALIC_SHAPE = {0, 25, 30, 0};
