#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText36");
#define CRIMSONTEXT_ROMAN_HANDLE 0
#define CRIMSONTEXT_ROMAN_WIDTH 38
#define CRIMSONTEXT_ROMAN_HEIGHT 50
#define CRIMSONTEXT_ROMAN_CELLS 96
#define ASSETS_END 91348UL
static const shape_t CRIMSONTEXT_ROMAN_SHAPE = {0, 38, 50, 0};
