#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Italic18");
#define CRIMSONTEXT_ITALIC_HANDLE 0
#define CRIMSONTEXT_ITALIC_WIDTH 18
#define CRIMSONTEXT_ITALIC_HEIGHT 22
#define CRIMSONTEXT_ITALIC_CELLS 96
#define ASSETS_END 19156UL
static const shape_t CRIMSONTEXT_ITALIC_SHAPE = {0, 18, 22, 0};
