#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBoldItalic24");
#define CRIMSONTEXT_SEMIBOLDITALIC_HANDLE 0
#define CRIMSONTEXT_SEMIBOLDITALIC_WIDTH 24
#define CRIMSONTEXT_SEMIBOLDITALIC_HEIGHT 32
#define CRIMSONTEXT_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 37012UL
static const shape_t CRIMSONTEXT_SEMIBOLDITALIC_SHAPE = {0, 24, 32, 0};
