#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBold9");
#define CRIMSONTEXT_SEMIBOLD_HANDLE 0
#define CRIMSONTEXT_SEMIBOLD_WIDTH 10
#define CRIMSONTEXT_SEMIBOLD_HEIGHT 12
#define CRIMSONTEXT_SEMIBOLD_CELLS 96
#define ASSETS_END 5908UL
static const shape_t CRIMSONTEXT_SEMIBOLD_SHAPE = {0, 10, 12, 0};
