#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBoldItalic18");
#define CRIMSONTEXT_SEMIBOLDITALIC_HANDLE 0
#define CRIMSONTEXT_SEMIBOLDITALIC_WIDTH 18
#define CRIMSONTEXT_SEMIBOLDITALIC_HEIGHT 24
#define CRIMSONTEXT_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 20884UL
static const shape_t CRIMSONTEXT_SEMIBOLDITALIC_SHAPE = {0, 18, 24, 0};
