#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBold18");
#define CRIMSONTEXT_SEMIBOLD_HANDLE 0
#define CRIMSONTEXT_SEMIBOLD_WIDTH 20
#define CRIMSONTEXT_SEMIBOLD_HEIGHT 24
#define CRIMSONTEXT_SEMIBOLD_CELLS 96
#define ASSETS_END 23188UL
static const shape_t CRIMSONTEXT_SEMIBOLD_SHAPE = {0, 20, 24, 0};
