#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText24");
#define CRIMSONTEXT_ROMAN_HANDLE 0
#define CRIMSONTEXT_ROMAN_WIDTH 26
#define CRIMSONTEXT_ROMAN_HEIGHT 33
#define CRIMSONTEXT_ROMAN_CELLS 96
#define ASSETS_END 41332UL
static const shape_t CRIMSONTEXT_ROMAN_SHAPE = {0, 26, 33, 0};
