#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Bold36");
#define CRIMSONTEXT_BOLD_HANDLE 0
#define CRIMSONTEXT_BOLD_WIDTH 38
#define CRIMSONTEXT_BOLD_HEIGHT 68
#define CRIMSONTEXT_BOLD_CELLS 96
#define ASSETS_END 124180UL
static const shape_t CRIMSONTEXT_BOLD_SHAPE = {0, 38, 68, 0};
