#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Italic36");
#define CRIMSONTEXT_ITALIC_HANDLE 0
#define CRIMSONTEXT_ITALIC_WIDTH 36
#define CRIMSONTEXT_ITALIC_HEIGHT 45
#define CRIMSONTEXT_ITALIC_CELLS 96
#define ASSETS_END 77908UL
static const shape_t CRIMSONTEXT_ITALIC_SHAPE = {0, 36, 45, 0};
