#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Italic24");
#define CRIMSONTEXT_ITALIC_HANDLE 0
#define CRIMSONTEXT_ITALIC_WIDTH 24
#define CRIMSONTEXT_ITALIC_HEIGHT 30
#define CRIMSONTEXT_ITALIC_CELLS 96
#define ASSETS_END 34708UL
static const shape_t CRIMSONTEXT_ITALIC_SHAPE = {0, 24, 30, 0};
