#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Italic12");
#define CRIMSONTEXT_ITALIC_HANDLE 0
#define CRIMSONTEXT_ITALIC_WIDTH 12
#define CRIMSONTEXT_ITALIC_HEIGHT 15
#define CRIMSONTEXT_ITALIC_CELLS 96
#define ASSETS_END 8788UL
static const shape_t CRIMSONTEXT_ITALIC_SHAPE = {0, 12, 15, 0};
