#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBold24");
#define CRIMSONTEXT_SEMIBOLD_HANDLE 0
#define CRIMSONTEXT_SEMIBOLD_WIDTH 26
#define CRIMSONTEXT_SEMIBOLD_HEIGHT 33
#define CRIMSONTEXT_SEMIBOLD_CELLS 96
#define ASSETS_END 41332UL
static const shape_t CRIMSONTEXT_SEMIBOLD_SHAPE = {0, 26, 33, 0};
