#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLightItalic24");
#define AILERON_ULTRALIGHTITALIC_HANDLE 0
#define AILERON_ULTRALIGHTITALIC_WIDTH 20
#define AILERON_ULTRALIGHTITALIC_HEIGHT 29
#define AILERON_ULTRALIGHTITALIC_CELLS 96
#define ASSETS_END 27988UL
static const shape_t AILERON_ULTRALIGHTITALIC_SHAPE = {0, 20, 29, 0};
