#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLightItalic12");
#define AILERON_ULTRALIGHTITALIC_HANDLE 0
#define AILERON_ULTRALIGHTITALIC_WIDTH 10
#define AILERON_ULTRALIGHTITALIC_HEIGHT 14
#define AILERON_ULTRALIGHTITALIC_CELLS 96
#define ASSETS_END 6868UL
static const shape_t AILERON_ULTRALIGHTITALIC_SHAPE = {0, 10, 14, 0};
