#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-boldItalic24");
#define AILERON_BOLDITALIC_HANDLE 0
#define AILERON_BOLDITALIC_WIDTH 24
#define AILERON_BOLDITALIC_HEIGHT 29
#define AILERON_BOLDITALIC_CELLS 96
#define ASSETS_END 33556UL
static const shape_t AILERON_BOLDITALIC_SHAPE = {0, 24, 29, 0};
