#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-blackItalic9");
#define AILERON_BLACKITALIC_HANDLE 0
#define AILERON_BLACKITALIC_WIDTH 10
#define AILERON_BLACKITALIC_HEIGHT 11
#define AILERON_BLACKITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t AILERON_BLACKITALIC_SHAPE = {0, 10, 11, 0};
