#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-ThinItalic36");
#define AILERON_THINITALIC_HANDLE 0
#define AILERON_THINITALIC_WIDTH 31
#define AILERON_THINITALIC_HEIGHT 43
#define AILERON_THINITALIC_CELLS 96
#define ASSETS_END 66196UL
static const shape_t AILERON_THINITALIC_SHAPE = {0, 31, 43, 0};
