#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBoldItalic36");
#define AILERON_SEMIBOLDITALIC_HANDLE 0
#define AILERON_SEMIBOLDITALIC_WIDTH 35
#define AILERON_SEMIBOLDITALIC_HEIGHT 43
#define AILERON_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 74452UL
static const shape_t AILERON_SEMIBOLDITALIC_SHAPE = {0, 35, 43, 0};
