#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLightItalic9");
#define AILERON_ULTRALIGHTITALIC_HANDLE 0
#define AILERON_ULTRALIGHTITALIC_WIDTH 9
#define AILERON_ULTRALIGHTITALIC_HEIGHT 11
#define AILERON_ULTRALIGHTITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t AILERON_ULTRALIGHTITALIC_SHAPE = {0, 9, 11, 0};
