#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLight24");
#define AILERON_ULTRALIGHT_HANDLE 0
#define AILERON_ULTRALIGHT_WIDTH 20
#define AILERON_ULTRALIGHT_HEIGHT 29
#define AILERON_ULTRALIGHT_CELLS 96
#define ASSETS_END 27988UL
static const shape_t AILERON_ULTRALIGHT_SHAPE = {0, 20, 29, 0};
