#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-ThinItalic18");
#define AILERON_THINITALIC_HANDLE 0
#define AILERON_THINITALIC_WIDTH 16
#define AILERON_THINITALIC_HEIGHT 22
#define AILERON_THINITALIC_CELLS 96
#define ASSETS_END 17044UL
static const shape_t AILERON_THINITALIC_SHAPE = {0, 16, 22, 0};
