#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-HeavyItalic36");
#define AILERON_HEAVYITALIC_HANDLE 0
#define AILERON_HEAVYITALIC_WIDTH 36
#define AILERON_HEAVYITALIC_HEIGHT 43
#define AILERON_HEAVYITALIC_CELLS 96
#define ASSETS_END 74452UL
static const shape_t AILERON_HEAVYITALIC_SHAPE = {0, 36, 43, 0};
