#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-blackItalic36");
#define AILERON_BLACKITALIC_HANDLE 0
#define AILERON_BLACKITALIC_WIDTH 37
#define AILERON_BLACKITALIC_HEIGHT 43
#define AILERON_BLACKITALIC_CELLS 96
#define ASSETS_END 78580UL
static const shape_t AILERON_BLACKITALIC_SHAPE = {0, 37, 43, 0};
