#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-HeavyItalic12");
#define AILERON_HEAVYITALIC_HANDLE 0
#define AILERON_HEAVYITALIC_WIDTH 12
#define AILERON_HEAVYITALIC_HEIGHT 14
#define AILERON_HEAVYITALIC_CELLS 96
#define ASSETS_END 8212UL
static const shape_t AILERON_HEAVYITALIC_SHAPE = {0, 12, 14, 0};
