#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-LightItalic9");
#define AILERON_LIGHTITALIC_HANDLE 0
#define AILERON_LIGHTITALIC_WIDTH 9
#define AILERON_LIGHTITALIC_HEIGHT 11
#define AILERON_LIGHTITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t AILERON_LIGHTITALIC_SHAPE = {0, 9, 11, 0};
