#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBoldItalic12");
#define AILERON_SEMIBOLDITALIC_HANDLE 0
#define AILERON_SEMIBOLDITALIC_WIDTH 12
#define AILERON_SEMIBOLDITALIC_HEIGHT 14
#define AILERON_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 8212UL
static const shape_t AILERON_SEMIBOLDITALIC_SHAPE = {0, 12, 14, 0};
