#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBold18");
#define AILERON_SEMIBOLD_HANDLE 0
#define AILERON_SEMIBOLD_WIDTH 18
#define AILERON_SEMIBOLD_HEIGHT 22
#define AILERON_SEMIBOLD_CELLS 96
#define ASSETS_END 19156UL
static const shape_t AILERON_SEMIBOLD_SHAPE = {0, 18, 22, 0};
