#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-boldItalic36");
#define AILERON_BOLDITALIC_HANDLE 0
#define AILERON_BOLDITALIC_WIDTH 36
#define AILERON_BOLDITALIC_HEIGHT 43
#define AILERON_BOLDITALIC_CELLS 96
#define ASSETS_END 74452UL
static const shape_t AILERON_BOLDITALIC_SHAPE = {0, 36, 43, 0};
