#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-blackItalic24");
#define AILERON_BLACKITALIC_HANDLE 0
#define AILERON_BLACKITALIC_WIDTH 25
#define AILERON_BLACKITALIC_HEIGHT 29
#define AILERON_BLACKITALIC_CELLS 96
#define ASSETS_END 36340UL
static const shape_t AILERON_BLACKITALIC_SHAPE = {0, 25, 29, 0};
