#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-UltraLight12");
#define AILERON_ULTRALIGHT_HANDLE 0
#define AILERON_ULTRALIGHT_WIDTH 10
#define AILERON_ULTRALIGHT_HEIGHT 14
#define AILERON_ULTRALIGHT_CELLS 96
#define ASSETS_END 6868UL
static const shape_t AILERON_ULTRALIGHT_SHAPE = {0, 10, 14, 0};
