#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBold12");
#define AILERON_SEMIBOLD_HANDLE 0
#define AILERON_SEMIBOLD_WIDTH 12
#define AILERON_SEMIBOLD_HEIGHT 14
#define AILERON_SEMIBOLD_CELLS 96
#define ASSETS_END 8212UL
static const shape_t AILERON_SEMIBOLD_SHAPE = {0, 12, 14, 0};
