#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBoldItalic18");
#define AILERON_SEMIBOLDITALIC_HANDLE 0
#define AILERON_SEMIBOLDITALIC_WIDTH 18
#define AILERON_SEMIBOLDITALIC_HEIGHT 22
#define AILERON_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 19156UL
static const shape_t AILERON_SEMIBOLDITALIC_SHAPE = {0, 18, 22, 0};
