#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-SemiBoldItalic24");
#define AILERON_SEMIBOLDITALIC_HANDLE 0
#define AILERON_SEMIBOLDITALIC_WIDTH 23
#define AILERON_SEMIBOLDITALIC_HEIGHT 29
#define AILERON_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 33556UL
static const shape_t AILERON_SEMIBOLDITALIC_SHAPE = {0, 23, 29, 0};
