#define LOAD_ASSETS()  GD.safeload("GD2Files\aileron-boldItalic18");
#define AILERON_BOLDITALIC_HANDLE 0
#define AILERON_BOLDITALIC_WIDTH 19
#define AILERON_BOLDITALIC_HEIGHT 22
#define AILERON_BOLDITALIC_CELLS 96
#define ASSETS_END 21268UL
static const shape_t AILERON_BOLDITALIC_SHAPE = {0, 19, 22, 0};
