#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeItalic9");
#define COURIER PRIME ITALIC_HANDLE 0
#define COURIER PRIME ITALIC_WIDTH 7
#define COURIER PRIME ITALIC_HEIGHT 9
#define COURIER PRIME ITALIC_CELLS 96
#define ASSETS_END 3604UL
static const shape_t COURIER PRIME ITALIC_SHAPE = {0, 7, 9, 0};
