#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeBoldItalic18");
#define COURIER PRIME BOLD ITALIC_HANDLE 0
#define COURIER PRIME BOLD ITALIC_WIDTH 13
#define COURIER PRIME BOLD ITALIC_HEIGHT 18
#define COURIER PRIME BOLD ITALIC_CELLS 96
#define ASSETS_END 12244UL
static const shape_t COURIER PRIME BOLD ITALIC_SHAPE = {0, 13, 18, 0};
