#define LOAD_ASSETS()  GD.safeload("GD2Files\CourierPrimeItalic36");
#define COURIER PRIME ITALIC_HANDLE 0
#define COURIER PRIME ITALIC_WIDTH 25
#define COURIER PRIME ITALIC_HEIGHT 36
#define COURIER PRIME ITALIC_CELLS 96
#define ASSETS_END 45076UL
static const shape_t COURIER PRIME ITALIC_SHAPE = {0, 25, 36, 0};
