#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Bold18");
#define CRIMSONTEXT_BOLD_HANDLE 0
#define CRIMSONTEXT_BOLD_WIDTH 21
#define CRIMSONTEXT_BOLD_HEIGHT 34
#define CRIMSONTEXT_BOLD_CELLS 96
#define ASSETS_END 36052UL
static const shape_t CRIMSONTEXT_BOLD_SHAPE = {0, 21, 34, 0};
