#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-Italic9");
#define CRIMSONTEXT_ITALIC_HANDLE 0
#define CRIMSONTEXT_ITALIC_WIDTH 9
#define CRIMSONTEXT_ITALIC_HEIGHT 11
#define CRIMSONTEXT_ITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t CRIMSONTEXT_ITALIC_SHAPE = {0, 9, 11, 0};
