#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBoldItalic12");
#define CRIMSONTEXT_SEMIBOLDITALIC_HANDLE 0
#define CRIMSONTEXT_SEMIBOLDITALIC_WIDTH 13
#define CRIMSONTEXT_SEMIBOLDITALIC_HEIGHT 16
#define CRIMSONTEXT_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 10900UL
static const shape_t CRIMSONTEXT_SEMIBOLDITALIC_SHAPE = {0, 13, 16, 0};
