#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-BoldItalic9");
#define CRIMSONTEXT_BOLDITALIC_HANDLE 0
#define CRIMSONTEXT_BOLDITALIC_WIDTH 10
#define CRIMSONTEXT_BOLDITALIC_HEIGHT 11
#define CRIMSONTEXT_BOLDITALIC_CELLS 96
#define ASSETS_END 5428UL
static const shape_t CRIMSONTEXT_BOLDITALIC_SHAPE = {0, 10, 11, 0};
