#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-BoldItalic12");
#define CRIMSONTEXT_BOLDITALIC_HANDLE 0
#define CRIMSONTEXT_BOLDITALIC_WIDTH 13
#define CRIMSONTEXT_BOLDITALIC_HEIGHT 15
#define CRIMSONTEXT_BOLDITALIC_CELLS 96
#define ASSETS_END 10228UL
static const shape_t CRIMSONTEXT_BOLDITALIC_SHAPE = {0, 13, 15, 0};
