#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-BoldItalic18");
#define CRIMSONTEXT_BOLDITALIC_HANDLE 0
#define CRIMSONTEXT_BOLDITALIC_WIDTH 19
#define CRIMSONTEXT_BOLDITALIC_HEIGHT 22
#define CRIMSONTEXT_BOLDITALIC_CELLS 96
#define ASSETS_END 21268UL
static const shape_t CRIMSONTEXT_BOLDITALIC_SHAPE = {0, 19, 22, 0};
