#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-BoldItalic36");
#define CRIMSONTEXT_BOLDITALIC_HANDLE 0
#define CRIMSONTEXT_BOLDITALIC_WIDTH 37
#define CRIMSONTEXT_BOLDITALIC_HEIGHT 45
#define CRIMSONTEXT_BOLDITALIC_CELLS 96
#define ASSETS_END 82228UL
static const shape_t CRIMSONTEXT_BOLDITALIC_SHAPE = {0, 37, 45, 0};
