#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBold36");
#define CRIMSONTEXT_SEMIBOLD_HANDLE 0
#define CRIMSONTEXT_SEMIBOLD_WIDTH 38
#define CRIMSONTEXT_SEMIBOLD_HEIGHT 49
#define CRIMSONTEXT_SEMIBOLD_CELLS 96
#define ASSETS_END 89524UL
static const shape_t CRIMSONTEXT_SEMIBOLD_SHAPE = {0, 38, 49, 0};
