#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBoldItalic9");
#define CRIMSONTEXT_SEMIBOLDITALIC_HANDLE 0
#define CRIMSONTEXT_SEMIBOLDITALIC_WIDTH 10
#define CRIMSONTEXT_SEMIBOLDITALIC_HEIGHT 12
#define CRIMSONTEXT_SEMIBOLDITALIC_CELLS 96
#define ASSETS_END 5908UL
static const shape_t CRIMSONTEXT_SEMIBOLDITALIC_SHAPE = {0, 10, 12, 0};
