#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText-SemiBold12");
#define CRIMSONTEXT_SEMIBOLD_HANDLE 0
#define CRIMSONTEXT_SEMIBOLD_WIDTH 13
#define CRIMSONTEXT_SEMIBOLD_HEIGHT 16
#define CRIMSONTEXT_SEMIBOLD_CELLS 96
#define ASSETS_END 10900UL
static const shape_t CRIMSONTEXT_SEMIBOLD_SHAPE = {0, 13, 16, 0};
