#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText18");
#define CRIMSONTEXT_ROMAN_HANDLE 0
#define CRIMSONTEXT_ROMAN_WIDTH 20
#define CRIMSONTEXT_ROMAN_HEIGHT 25
#define CRIMSONTEXT_ROMAN_CELLS 96
#define ASSETS_END 24148UL
static const shape_t CRIMSONTEXT_ROMAN_SHAPE = {0, 20, 25, 0};
