#define LOAD_ASSETS()  GD.safeload("GD2Files\CrimsonText12");
#define CRIMSONTEXT_ROMAN_HANDLE 0
#define CRIMSONTEXT_ROMAN_WIDTH 13
#define CRIMSONTEXT_ROMAN_HEIGHT 17
#define CRIMSONTEXT_ROMAN_CELLS 96
#define ASSETS_END 11572UL
static const shape_t CRIMSONTEXT_ROMAN_SHAPE = {0, 13, 17, 0};
